// Page Titles
window.titles = {
    overview: 'Overview',
    electricity_market: 'Electricity Market',
    spot_market: 'Spot Market',
    arbitrage_points: 'Arbitrage Points',
    trading: 'Trading',
    trading_rules: 'Trading Rules',
    trading_events: 'Trading Events',
    smart_feed_in: 'Smart Feed-in',
    smart_feed_in_rules: 'Smart Feed-in Rules',
    smart_feed_in_events: 'Smart Feed-in Events',
    cap_service: 'Cap Service',
    cap_graph: 'Cap Graph',
    cap_rules: 'Cap Rules',
    cap_events: 'Cap Events',
    fcas: 'FCAS',
    fcas_groups: 'FCAS Groups',
    fcas_price_availability: 'Price and Availability',
    reports: 'Reports',
    reports_vpp_events: 'VPP Events',
    reports_der_events: 'DER Events',
    reports_vpp_event_items: 'VPP Event Items',
    reports_vpp_event_month_summary: 'VPP Event Month Summary',
    reports_terminated: 'Terminated',
    vpp: 'VPP Management',
    vpp_details: 'VPP Details',
    device_management: 'Device Connection',
    system_details: 'System Details',
    system: 'System',
    account: 'Account'
};
